name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply Terraform
        run: terraform apply -var-file="terraform.tfvars" -auto-approve
